services:
  postgres_account:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
  postgres_ride:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    ports:
      - "5433:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
  postgres_payment:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    ports:
      - "5434:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
  postgres_reader:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    ports:
      - "5435:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - 5672:5672
      - 15672:15672
